# NOTE: cdist = 48 and ckl = 1 by default in main

WANDB_MODE=online CUDA_VISIBLE_DEVICES=0 python main_clap.py --wandb_name clap_ht_fused_multiMpnet_audiocaps_clotho_wavcaps --mode train --num_batch 1000000000000 --epochs 50 --emb_method "no_skip_conn" --loss_method mse_klclip --train_langs audiocaps_train_45K clotho_train_from_wavcaps_19K wavcaps_train_304K --audio_model clap --text_model multiMpnet --eng_base_path ./content/drive/MyDrive/clip-data/AWS\ 68\ Languages/unique_texts_pre/ --img_to_text_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_img_to_text_map.pkl --text_to_img_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_text_to_img_map.pkl --audio_base_dir ./eval_data/audio_dataset/val/

WANDB_MODE=online CUDA_VISIBLE_DEVICES=0 python main_clap.py --wandb_name clap_general_multiMpnet_audiocaps_clotho_wavcaps --mode train --num_batch 1000000000000 --epochs 50 --emb_method "no_skip_conn" --loss_method mse_klclip --train_langs audiocaps_train_45K clotho_train_from_wavcaps_19K wavcaps_train_304K --audio_model clap_general --text_model multiMpnet --eng_base_path ./content/drive/MyDrive/clip-data/AWS\ 68\ Languages/unique_texts_pre/ --img_to_text_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_img_to_text_map.pkl --text_to_img_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_text_to_img_map.pkl --audio_base_dir ./eval_data/audio_dataset/val/


#WANDB_MODE=online CUDA_VISIBLE_DEVICES=1 python main_clap.py --wandb_name clap_ht_fused_multiMpnet_audiocaps --mode train --num_batch 1000000000000 --epochs 50 --emb_method "no_skip_conn" --loss_method mse_klclip --train_langs audiocaps_train_45K --audio_model clap --text_model multiMpnet --eng_base_path ./content/drive/MyDrive/clip-data/AWS\ 68\ Languages/unique_texts_pre/ --img_to_text_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_img_to_text_map.pkl --text_to_img_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_text_to_img_map.pkl --audio_base_dir ./eval_data/audio_dataset/val/

#WANDB_MODE=online CUDA_VISIBLE_DEVICES=1 python main_clap.py --wandb_name clap_general_multiMpnet_audiocaps --mode train --num_batch 1000000000000 --epochs 50 --emb_method "no_skip_conn" --loss_method mse_klclip --train_langs audiocaps_train_45K --audio_model clap_general --text_model multiMpnet --eng_base_path ./content/drive/MyDrive/clip-data/AWS\ 68\ Languages/unique_texts_pre/ --img_to_text_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_img_to_text_map.pkl --text_to_img_map_path ./eval_data/audio_dataset/audiocaps/dataset/val_text_to_img_map.pkl --audio_base_dir ./eval_data/audio_dataset/val/


